connection:
  HOST: 127.0.0.1
  port: 9222
  user_data_dir: data/chromium_user_data
  headless: false
  no_sandbox: true

search:
  base_url: "https://www.linkedin.com/jobs/search-results/"
  query: "Data Engineer"
  easy_apply: true
#  geo_id: 102299470
  geo_id: 105214831
  max_jobs: 15

langchain:
  use_ai: true
  use_chatgpt: false
  using_ollama: true
#  model_name: "gpt-4o"
  model_name: "qwen2.5-coder:7b-instruct-q4_K_M"
  temperature: 0.7

user_data:
  info_file: data/my_info.txt
  resume_file: data/my_resume.pdf